### ISSUE TITLE
包含 .useOcclusionPlanes 的结构体在工程中找不到。

### ISSUE THREAD

**Issue by HuaianWu** [duzexu/ARuler#1]
`
if UserDefaults.standardforforKey: .useOcclusionPlanes) {
			updateOcclusionNode()
		}
`

如题，还有工程中 3 个 swift 文件的引用似乎有问题，如要重新导入才能编译。😊

**Comment by EdwinCXD** [comment]
@HuaianWu  倒入Apple ARDemo 里的SettingsViewController.swift就好了
