### ISSUE TITLE
Apple Mach-O Linker (ld) Error Group

### ISSUE THREAD

**Issue by WOOOFEI** [duzexu/ARuler#12]
I cant figure it out. 😫
![1506409289910](https://user-images.githubusercontent.com/21849553/30847378-ebe70550-a2cd-11e7-923a-16c5320740f4.jpg)

**Comment by WOOOFEI** [comment]
![111](https://user-images.githubusercontent.com/21849553/30847502-5c414068-a2ce-11e7-9002-1e89b5cb92eb.jpg)

i cant find Pods_ARuler.framework after "pod install"

**Comment by duzexu** [comment]
You should open ARuler.xcworkspace instead.
