### ISSUE TITLE
missing Settings.swift

### ISSUE THREAD

**Issue by pteasima** [duzexu/ARuler#3]
Hi, looks like you forgot to commit the file Settings.swift

**Comment by feraco** [comment]
Hi this project looks great but we need the settings.swift file Can you add it?

**Comment by kerinzeebart** [comment]
Yep, missing settings. Anyone have a idea how to get this to run?

**Comment by pteasima** [comment]
guys, stop spamming the poor guy, im sure he will commit the file asap. If you want to get this to run yourself, just implement the missing methods on UserDefaults and the missing Settings enum. I just prefer to wait...

**Comment by bre7** [comment]
~~Settings.swift is probably just a ref to a deleted file. You can delete it and add the appropriate function as an extension in UserDefaults~~

Link `SettingsViewController.swift` to the project

**Comment by kerinzeebart** [comment]
Was Able to relink the file fine and compiled the project. However the measurement doesn’t work when I hit the + button.

**Comment by bre7** [comment]
It works, you just need to "move the phone around" to perform plane detection.

https://github.com/duzexu/ARuler/blob/master/ARuler/ViewController.swift#L234
Google translate "请左右移动您的手机" -> "Please move your phone around left and right"

**Comment by duzexu** [comment]
I have delete unused code and the last commit have fix this issue

I will add Localization in the future to support english
