### ISSUE TITLE
May I ask a question?

### ISSUE THREAD

**Issue by hzhou81** [duzexu/ARuler#5]
Can I measure distance from somewhere far away from here to here, for example, when I am on the road, I saw a tower is just 500 meter away from here, can this measure the distance?

请问，我可以测量水平距离吗？比如说，我在路上，看到一个距离我500米左右的灯塔，我能不能测量我和灯塔之间的具体距离？

**Comment by duzexu** [comment]
我没有在苹果的官方文档上看到具体的说明，不过根据 http://www.jianshu.com/p/d7dcf46f3705 这篇文章的说明，苹果工程师说100米左右是 ARKit 在保持较好用户体验的最大测量距离，所以500可能不行
