### ISSUE TITLE
测量稳定性和线条属性

### ISSUE THREAD

**Issue by ukmak** [duzexu/ARuler#6]
1. 有时候起始点会自动移动，然后移动手机，终点会瞎跑；
2. 可以测量斜面吗；
3. 能不能修改线条的属性（线宽、颜色等）。

**Comment by duzexu** [comment]
1.我测试的时候也发生过，尽量保证背景颜色不单一，特征点比较多的情况会好很多，之后再加上特征点的过滤应该会好很多
2.新更新的应该可以了，不过测得也不是很准
3.这个我也接触scenekit，还不知道(￣▽￣)~*

**Comment by ukmak** [comment]
特征点根据什么原则过滤的？
最新更新的代码编译报错，麻烦帮忙看一下
![snip20170802_1](https://user-images.githubusercontent.com/30622831/28853602-3c39abd8-7764-11e7-9a6a-c09601c3b244.png)

**Comment by duzexu** [comment]
编译错误看一下readme 运行部分
过滤就是用的方差和标准差简单过滤了一下
